FROM ubuntu:latest

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y python3 && apt-get install -y python3-pip git wget
RUN apt-get install -y python3-tk libgtk2.0-dev

WORKDIR /home/mrcnn/
COPY ./mrcnn-ms/requirements.txt .

RUN pip3 install -r requirements.txt

EXPOSE 80

CMD bash mask.sh
