FROM ubuntu:latest

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y python3 && apt-get install -y pip3 git 

WORKDIR /home/mrcnn/

RUN git clone https://github.com/matterport/Mask_RCNN.git

RUN git clone https://github.com/philferriere/cocoapi.git

RUN pip3 install -r requirements.txt

RUN pip3 install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI

EXPOSE 80

CMD python3 MaskRCNN.py

